SELECT ?region ?regionLabel (COUNT(?item) AS ?cnt)
WHERE {
    ?item wdt:P31 wd:Q1248784 ;
          wdt:P17 wd:Q183 ;
          wdt:P131 ?region .
    SERVICE wikibase:label {
        bd:serviceParam wikibase:language "en"
    }
}
GROUP BY ?region ?regionLabel
HAVING(COUNT(?item) >= 3)
ORDER BY DESC(?cnt) ?region
LIMIT 10