SELECT ?item ?itemLabel ?region ?regionLabel ?population
WHERE {
    ?item wdt:P31 wd:Q1248784 ;
          wdt:P17 wd:Q183 ;
          wdt:P131 ?region .
    ?region wdt:P1082 ?population .
    SERVICE wikibase:label {
        bd:serviceParam wikibase:language "en"
    }
}
ORDER BY DESC(?population) ?item
LIMIT 10